Add remaining scalar types to inferJSONSchemaType
mercurius-js/validation pull request #89
Opened 2024-03-14 09:17 UTC by bilalshareef

Fix #29

2024-03-18 09:22 UTC, simoneb commented on test/json-schema-validation.js
> +    t.plan(1)
this is unnecessay

2024-03-18 10:13 UTC, bilalshareef commented on test/json-schema-validation.js
> +    t.plan(1)
I removed it now.

2024-03-18 10:25 UTC, simoneb requested changes
I tihnk we need to review the logic here. If somebody provides a custom inference function, we surely need to invoke it, but that doesn't necessarily mean that it will hande the scalar type we're currently processing. Meaning that we need to define AND document a signature for that function, because users need to know how to use it and what to return from it.

The behavior should be this:

- the custom function can override the default logic, meaning that it should be invoked first
- the signature should be so that if the custom function doesn't handle the type, it returns a falsy value, in which case the default logic kicks in

2024-03-19 09:05 UTC, simoneb approved these changes

2024-03-19 18:45 UTC, jonnydgreen approved these changes
LGTM - fantastic work!

2024-03-19 18:46 UTC, jonnydgreen commented
Will aim to include as part of the next release if that works :)

2024-03-20 22:37 UTC, merged